/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.TURTLE;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>TURTLE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.TURTLEImpl#getStartPosX <em>Start Pos X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.TURTLEImpl#getStartPosY <em>Start Pos Y</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TURTLEImpl extends CMDImpl implements TURTLE
{
  /**
   * The default value of the '{@link #getStartPosX() <em>Start Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartPosX()
   * @generated
   * @ordered
   */
  protected static final int START_POS_X_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStartPosX() <em>Start Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartPosX()
   * @generated
   * @ordered
   */
  protected int startPosX = START_POS_X_EDEFAULT;

  /**
   * The default value of the '{@link #getStartPosY() <em>Start Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartPosY()
   * @generated
   * @ordered
   */
  protected static final int START_POS_Y_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStartPosY() <em>Start Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartPosY()
   * @generated
   * @ordered
   */
  protected int startPosY = START_POS_Y_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TURTLEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TURTLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getStartPosX()
  {
    return startPosX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStartPosX(int newStartPosX)
  {
    int oldStartPosX = startPosX;
    startPosX = newStartPosX;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.TURTLE__START_POS_X, oldStartPosX, startPosX));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getStartPosY()
  {
    return startPosY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStartPosY(int newStartPosY)
  {
    int oldStartPosY = startPosY;
    startPosY = newStartPosY;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.TURTLE__START_POS_Y, oldStartPosY, startPosY));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.TURTLE__START_POS_X:
        return getStartPosX();
      case MyDslPackage.TURTLE__START_POS_Y:
        return getStartPosY();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.TURTLE__START_POS_X:
        setStartPosX((Integer)newValue);
        return;
      case MyDslPackage.TURTLE__START_POS_Y:
        setStartPosY((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TURTLE__START_POS_X:
        setStartPosX(START_POS_X_EDEFAULT);
        return;
      case MyDslPackage.TURTLE__START_POS_Y:
        setStartPosY(START_POS_Y_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TURTLE__START_POS_X:
        return startPosX != START_POS_X_EDEFAULT;
      case MyDslPackage.TURTLE__START_POS_Y:
        return startPosY != START_POS_Y_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (startPosX: ");
    result.append(startPosX);
    result.append(", startPosY: ");
    result.append(startPosY);
    result.append(')');
    return result.toString();
  }

} //TURTLEImpl
