/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.web;

import org.xtext.example.mydsl.web.AbstractMyDslWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MyDslWebModule extends AbstractMyDslWebModule {
}
