/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MyDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMyDslWebModule extends DefaultWebModule {

}
