/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>PROGRAM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PROGRAM</em>'.
   * @generated
   */
  PROGRAM createPROGRAM();

  /**
   * Returns a new object of class '<em>CMD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CMD</em>'.
   * @generated
   */
  CMD createCMD();

  /**
   * Returns a new object of class '<em>PAPER</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAPER</em>'.
   * @generated
   */
  PAPER createPAPER();

  /**
   * Returns a new object of class '<em>TURTLE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TURTLE</em>'.
   * @generated
   */
  TURTLE createTURTLE();

  /**
   * Returns a new object of class '<em>PENSTATE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PENSTATE</em>'.
   * @generated
   */
  PENSTATE createPENSTATE();

  /**
   * Returns a new object of class '<em>PENCOLOUR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PENCOLOUR</em>'.
   * @generated
   */
  PENCOLOUR createPENCOLOUR();

  /**
   * Returns a new object of class '<em>MOVE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MOVE</em>'.
   * @generated
   */
  MOVE createMOVE();

  /**
   * Returns a new object of class '<em>RIGHT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RIGHT</em>'.
   * @generated
   */
  RIGHT createRIGHT();

  /**
   * Returns a new object of class '<em>LEFT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LEFT</em>'.
   * @generated
   */
  LEFT createLEFT();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
