/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAPER</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PAPER#getSizeX <em>Size X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PAPER#getSizeY <em>Size Y</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PAPER#getPaperColour <em>Paper Colour</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPAPER()
 * @model
 * @generated
 */
public interface PAPER extends CMD
{
  /**
   * Returns the value of the '<em><b>Size X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size X</em>' attribute.
   * @see #setSizeX(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPAPER_SizeX()
   * @model
   * @generated
   */
  int getSizeX();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PAPER#getSizeX <em>Size X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size X</em>' attribute.
   * @see #getSizeX()
   * @generated
   */
  void setSizeX(int value);

  /**
   * Returns the value of the '<em><b>Size Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size Y</em>' attribute.
   * @see #setSizeY(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPAPER_SizeY()
   * @model
   * @generated
   */
  int getSizeY();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PAPER#getSizeY <em>Size Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size Y</em>' attribute.
   * @see #getSizeY()
   * @generated
   */
  void setSizeY(int value);

  /**
   * Returns the value of the '<em><b>Paper Colour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paper Colour</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paper Colour</em>' attribute.
   * @see #setPaperColour(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPAPER_PaperColour()
   * @model
   * @generated
   */
  String getPaperColour();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PAPER#getPaperColour <em>Paper Colour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paper Colour</em>' attribute.
   * @see #getPaperColour()
   * @generated
   */
  void setPaperColour(String value);

} // PAPER
