/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PENCOLOUR</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PENCOLOUR#getColour <em>Colour</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPENCOLOUR()
 * @model
 * @generated
 */
public interface PENCOLOUR extends CMD
{
  /**
   * Returns the value of the '<em><b>Colour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Colour</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colour</em>' attribute.
   * @see #setColour(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPENCOLOUR_Colour()
   * @model
   * @generated
   */
  String getColour();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PENCOLOUR#getColour <em>Colour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colour</em>' attribute.
   * @see #getColour()
   * @generated
   */
  void setColour(String value);

} // PENCOLOUR
