/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TURTLE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TURTLE#getStartPosX <em>Start Pos X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TURTLE#getStartPosY <em>Start Pos Y</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTURTLE()
 * @model
 * @generated
 */
public interface TURTLE extends CMD
{
  /**
   * Returns the value of the '<em><b>Start Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start Pos X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Pos X</em>' attribute.
   * @see #setStartPosX(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTURTLE_StartPosX()
   * @model
   * @generated
   */
  int getStartPosX();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TURTLE#getStartPosX <em>Start Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Pos X</em>' attribute.
   * @see #getStartPosX()
   * @generated
   */
  void setStartPosX(int value);

  /**
   * Returns the value of the '<em><b>Start Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start Pos Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Pos Y</em>' attribute.
   * @see #setStartPosY(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTURTLE_StartPosY()
   * @model
   * @generated
   */
  int getStartPosY();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TURTLE#getStartPosY <em>Start Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Pos Y</em>' attribute.
   * @see #getStartPosY()
   * @generated
   */
  void setStartPosY(int value);

} // TURTLE
